services:
  - type: web
    name: voicebot-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000
    plan: free
    region: oregon

  - type: web
    name: voicebot-frontend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port 8501
    envVars:
      - key: PORT
        value: 8501
    plan: free
    region: oregon
